### ISSUE TITLE
Post page

### ISSUE THREAD

**Issue by IsTheMartin** [IsTheMartin/mrtnmrls#38]
### Subject of the issue
Create a dedicated page for posts (spanish and english) and display a list of posts.

### Evidences
A screenshot, gif or video

### Tasks
- [ ] Post page for spanish lang
- [ ] Post page for english lang
- [ ] Found a way to call those pages
